airlineManagement/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('website.urls'))
]

website/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path
from .views import *

urlpatterns = [
    path('', home, name='home'),
    path('logout/', logout_user, name='logout'),
    path('register/', register_user, name='register'),

    #-- users --#
    path('users/', UserManagement.list_users, name='list_users'),
    path('users/add/', UserManagement.add_user, name='add_user'),
    path('users/edit/<int:user_id>/', UserManagement.edit_user, name='edit_user'),
    path('users/delete/<int:user_id>/', UserManagement.delete_user, name='delete_user'),

    #-- planes --#
    path('planes/', PlaneClass.view_planes, name='view_planes'),
    path('planes/<int:serial_num>', PlaneClass.view_plane, name='view_plane'),
    path('delete_plane/<int:serial_num>', PlaneClass.delete_plane, name='delete_plane'),
    path('add_plane', PlaneClass.add_plane, name='add_plane'),
    path('update_plane/<int:serial_num>', PlaneClass.update_plane, name='update_plane'),

    #-- cities --#
    path('cities/', CityClass.view_cities, name='view_cities'),
    path('cities/<str:city_code>', CityClass.view_city, name='view_city'),
    path('delete_city/<str:city_code>', CityClass.delete_city, name='delete_city'),
    path('add_city', CityClass.add_city, name='add_city'),
    path('update_city/<str:city_code>', CityClass.update_city, name='update_city'),

    #-- flight crews --#
    #path('crews/', view_crews, name='view_crews'),
    #path('crews/<int:flight_num>/<int:employee_num>', view_crew, name='view_crew'),
    path('delete_crew/<int:flight_num>/<int:employee_num>', FlightClass.delete_crew, name='delete_crew'),
    path('add_crew/<int:flight_num>', FlightClass.add_crew, name='add_crew'),

    #-- flights --#
    path('flights/', FlightClass.view_flights, name='view_flights'),
    path('flights/<int:flight_num>', FlightClass.view_flight, name='view_flight'),
    path('delete_flight/<int:flight_num>', FlightClass.delete_flight, name='delete_flight'),
    path('add_flight', FlightClass.add_flight, name='add_flight'),
    path('update_flight/<int:flight_num>', FlightClass.update_flight, name='update_flight'),

    #-- passenger address --#
    #path('passenger_addresses/', view_passenger_addresses, name='view_passenger_addresses'),
    #path('passenger_addresses/<int:passenger_num>/<str:passenger_address>', view_passenger_address, name='view_passenger_address'),
    path('delete_passenger_address/<int:passenger_num>/<str:address>', PassengerClass.delete_passenger_address, name='delete_passenger_address'),
    path('add_passenger_address/<int:passenger_num>', PassengerClass.add_passenger_address, name='add_passenger_address'),

    #-- passenger booking --#
    #path('bookings/', view_passenger_bookings, name='view_passenger_bookings'),
    #path('bookings/<int:passenger_num>/<int:flight_num>', view_passenger_booking, name='view_passenger_booking'),
    path('delete_booking/<int:flight_num>/<int:passenger_num>', FlightClass.delete_passenger_booking, name='delete_passenger_booking'),
    path('add_booking/<int:flight_num>', FlightClass.add_passenger_booking, name='add_passenger_booking'),

    #-- passenger phone --#
    #path('passenger_phones/', view_passenger_phones, name='view_passenger_phones'),
    #path('passenger_phones/<str:phone>', view_passenger_phone, name='view_passenger_phone'),
    path('delete_passenger_phone/<str:phone>', PassengerClass.delete_passenger_phone, name='delete_passenger_phone'),
    path('add_passenger_phone/<int:passenger_num>', PassengerClass.add_passenger_phone, name='add_passenger_phone'),

    #-- passenger --#
    path('passengers/', PassengerClass.view_passengers, name='view_passengers'),
    path('passengers/<int:passenger_num>', PassengerClass.view_passenger, name='view_passenger'),
    path('delete_passenger/<int:passenger_num>', PassengerClass.delete_passenger, name='delete_passenger'),
    path('add_passenger', PassengerClass.add_passenger, name='add_passenger'),
    path('update_passenger/<int:passenger_num>', PassengerClass.update_passenger, name='update_passenger'),

    #-- pilot typeratings --#
    #path('pilot_typeratings/', view_pilot_typeratings, name='view_pilot_typeratings'),
    #path('pilot_typeratings/<int:pilot_num>/<str:typerating>', view_pilot_typerating, name='view_pilot_typerating'),
    path('delete_pilot_typerating/<int:pilotnum>/<str:typerating>', PilotClass.delete_pilot_typerating, name='delete_pilot_typerating'),
    path('add_pilot_typerating/<int:employee_num>', PilotClass.add_pilot_typerating, name='add_pilot_typerating'),

    #-- pilots --#
    path('pilots/', PilotClass.view_pilots, name='view_pilots'),
    path('pilots/<int:pilot_num>', PilotClass.view_pilot, name='view_pilot'),
    path('delete_pilot/<int:pilot_num>', PilotClass.delete_pilot, name='delete_pilot'),
    path('add_pilot', PilotClass.add_pilot, name='add_pilot'),
    path('update_pilot/<int:pilot_num>', PilotClass.update_pilot, name='update_pilot'),

    #-- staff addresses --#
    #path('staff_addresses/', view_staff_addresses, name='view_staff_addresses'),
    #path('staff_addresses/<int:employee_num>/<str:address>', view_staff_address, name='view_staff_address'),
    path('delete_staff_address/<int:employee_num>/<str:address>', StaffClass.delete_staff_address, name='delete_staff_address'),
    path('add_staff_address/<int:employee_num>', StaffClass.add_staff_address, name='add_staff_address'),

    #-- staff phones --#
    #path('staff_phones/', view_staff_phones, name='view_staff_phones'),
    #path('staff_phones/<str:phone>', view_staff_phone, name='view_staff_phone'),
    path('delete_staff_phone/<str:phone>', StaffClass.delete_staff_phone, name='delete_staff_phone'),
    path('add_staff_phone/<str:employee_num>', StaffClass.add_staff_phone, name='add_staff_phone'),
    
    #-- staff --#
    path('staff/', StaffClass.view_staff, name='view_staff'),
    path('staff/<int:employee_num>', StaffClass.view_staff_member, name='view_staff_member'),
    path('delete_staff/<int:employee_num>', StaffClass.delete_staff_member, name='delete_staff_member'),
    path('add_staff_member', StaffClass.add_staff_member, name='add_staff_member'),
    path('update_Staff_member/<int:employee_num>', StaffClass.update_staff_member, name='update_staff_member'),
    
    #-- stretch --#
    #path('stretches/', view_stretches, name='view_stretches'),
    #path('stretches/<int:stretch_num>', view_stretch, name='view_stretch'),
    path('delete_intermediate_city/<int:stretch_num>', FlightClass.delete_intermediate_city, name='delete_intermediate_city'),
    path('add_intermediate_city/<int:flight_num>', FlightClass.add_intermediate_city, name='add_intermediate_city'),

]

website/models.py
from django.db import models
from django.core.exceptions import ValidationError
from django.utils.translation import gettext_lazy as _

class Airplane(models.Model):
    SERIALNUM = models.IntegerField(primary_key=True)
    MANUFACTURER = models.CharField(max_length=10)
    MODEL = models.CharField(max_length=10)

class City(models.Model):
    CITYCODE = models.CharField(max_length=4, primary_key=True)
    CITYNAME = models.CharField(max_length=20)

class Staff(models.Model):
    EMPNUM = models.IntegerField(primary_key=True)
    SURNAME = models.CharField(max_length=30)
    NAME = models.CharField(max_length=20)
    SALARY = models.DecimalField(max_digits=10, decimal_places=2)
    TYPE = models.CharField(max_length=10)
    
    def clean(self):
        if self.TYPE not in ['Crew', 'Pilot']:
            raise ValidationError(_('Staff type must be "Crew" or "Pilot".'))

    def save(self, *args, **kwargs):
        self.full_clean()  # Ensure clean is called before saving
        super().save(*args, **kwargs)

class Pilot(models.Model):
    PILOTNUM = models.IntegerField(primary_key=True)
    EMPNUM = models.ForeignKey(Staff, on_delete=models.CASCADE)

class Flight(models.Model):
    FLIGHTNUM = models.IntegerField(primary_key=True)
    ORIGINCITYCODE = models.ForeignKey(City, on_delete=models.CASCADE, related_name='origin_flights')
    DESTCITYCODE = models.ForeignKey(City, on_delete=models.CASCADE, related_name='destination_flights')
    DEPTIME = models.DateTimeField()
    ARRTIME = models.DateTimeField()
    PILOTNUM = models.ForeignKey(Pilot, on_delete=models.CASCADE, related_name='pilot_flights')
    PLANENUM = models.ForeignKey(Airplane, on_delete=models.CASCADE, related_name='airplane_flights')

class FlightCrew(models.Model):
    FLIGHTNUM = models.ForeignKey(Flight, on_delete=models.CASCADE)
    EMPNUM = models.ForeignKey(Staff, on_delete=models.CASCADE, limit_choices_to={'TYPE': 'Crew'})
    class Meta:
        unique_together = (('FLIGHTNUM', 'EMPNUM'),)

class Passenger(models.Model):
    PASSENGERNUM = models.IntegerField(primary_key=True)
    SURNAME = models.CharField(max_length=30)
    NAME = models.CharField(max_length=20)

class PassengerAddress(models.Model):
    ADDRESSDETAILS = models.CharField(max_length=50)
    PASSENGERNUM = models.ForeignKey(Passenger, on_delete=models.CASCADE)
    class Meta:
        unique_together = (('PASSENGERNUM', 'ADDRESSDETAILS'),)

class PassengerBooking(models.Model):
    PASSENGERNUM = models.ForeignKey(Passenger, on_delete=models.CASCADE)
    FLIGHTNUM = models.ForeignKey(Flight, on_delete=models.CASCADE)
    class Meta:
        unique_together = (('PASSENGERNUM', 'FLIGHTNUM'),)

class PassengerPhone(models.Model):
    PHONE = models.CharField(max_length=15, primary_key=True)
    PASSENGERNUM = models.ForeignKey(Passenger, on_delete=models.CASCADE)



class PilotTypeRating(models.Model):
    TYPERATING = models.CharField(max_length=20)
    PILOTNUM = models.ForeignKey(Pilot, on_delete=models.CASCADE)
    DATEEARNED = models.DateTimeField()
    class Meta:
        unique_together = (('TYPERATING', 'PILOTNUM'),)



class StaffAddress(models.Model):
    ADDRESSDETAILS = models.CharField(max_length=50)
    EMPNUM = models.ForeignKey(Staff, on_delete=models.CASCADE)
    class Meta:
        unique_together = (('EMPNUM', 'ADDRESSDETAILS'),)

class StaffPhone(models.Model):
    PHONE = models.CharField(max_length=15, primary_key=True)
    EMPNUM = models.ForeignKey(Staff, on_delete=models.CASCADE)

class IntermediateCity(models.Model):
    STRETCHNUM = models.AutoField(primary_key=True)
    INTERMEDIATECITYCODE = models.ForeignKey(City, on_delete=models.CASCADE, related_name='intermediate_stretch_city')
    #DESTCITYCODE = models.ForeignKey(City, on_delete=models.CASCADE, related_name='destination_stretches')
    FLIGHTNUM = models.ForeignKey(Flight, on_delete=models.CASCADE)
    ARRTIME = models.DateTimeField()
    DEPTIME = models.DateTimeField()

website/templates/add_intermediate_city.html
{% extends 'base.html' %}
{% block content %}

<div class="col-md-6 offset-md-3">
    <h1>Add Intermediate City for Flight: {{ flight.FLIGHTNUM }}</h1>
    <br>

    <form method="POST">
        {% csrf_token %}

        {{ form.as_p }}
        <br>
        <a onclick="history.back()" class="btn btn-secondary">Cancel</a>
        <button type="submit" class="btn btn-primary">Add</button>


    </form>

</div>
{%endblock%}

website/templates/add_passenger_phone.html
{% extends 'base.html' %}
{% block content %}

<div class="col-md-6 offset-md-3">
    <h1>Add Passenger Phone</h1>
    <br>

    <form method="POST">
        {% csrf_token %}

        {{ form.as_p }}
        <br>
        <a onclick="history.back()" class="btn btn-secondary">Cancel</a>
        <button type="submit" class="btn btn-primary">Add</button>


    </form>

</div>
{%endblock%}

website/templates/add_pilot.html
{% extends 'base.html' %}
{% block content %}

<div class="col-md-6 offset-md-3">
    <h1>Add Pilot</h1>
    <br>

    <form method="POST" action="{% url 'add_pilot' %}">
        {% csrf_token %}

        {{ form.as_p }}
        <br>
        <a href="{% url 'view_pilots' %}" class="btn btn-secondary">Back</a>
        <button type="submit" class="btn btn-primary">Add</button>


    </form>

</div>
{%endblock%}

website/templates/add_pilot_typerating.html
{% extends 'base.html' %}
{% block content %}

<div class="col-md-6 offset-md-3">
    <h1>Add Pilot Type Rating</h1>
    <br>

    <form method="POST">
        {% csrf_token %}

        {{ form.as_p }}
        <br>
        <a onclick="history.back()" class="btn btn-secondary">Cancel</a>
        <button type="submit" class="btn btn-primary">Add</button>


    </form>

</div>
{%endblock%}

website/templates/add_staff_member.html
{% extends 'base.html' %}
{% block content %}

<div class="col-md-6 offset-md-3">
    <h1>Add Staff Member</h1>
    <br>
    <form method="POST" action="{% url 'add_staff_member' %}">
        {% csrf_token %}

        <!--<div id="pilotnum-container" style="display: none;">
            {{ form.pilotnum }}
        </div>-->
        <div class="form-group">
            {{ form.EMPNUM.label_tag }}
            {{ form.EMPNUM }}
        </div>

        <div class="form-group">
            {{ form.SURNAME.label_tag }}
            {{ form.SURNAME }}
        </div>

        <div class="form-group">
            {{ form.NAME.label_tag }}
            {{ form.NAME }}
        </div>
        <br>
        <div class="form-group">
            <div class="input-group">
                <div class="input-group-prepend">
                    <span class="input-group-text">$</span>
                </div>
                {{ form.SALARY }}
                <div class="input-group-append">
                    <span class="input-group-text">.00</span>
                </div>
            </div>
        </div>

        <div class="form-group">
            {{ form.TYPE.label_tag }}
            {{ form.TYPE }}
        </div>

        <div class="form-group">
            {{ form.pilotnum.label_tag }}
            {{ form.pilotnum }}
        </div>
        <br>
        <div id="addresses-container">
            {{ address_formset.management_form }}
            {% for form in address_formset %}
            <div class="address-form">
                <div class="input-button-container">
                    {{ form.as_p }}
                    <button type="button" class="btn btn-danger remove-address">
                        Remove Address
                    </button>
                </div>
            </div>
            {% endfor %}
        </div>
        <button type="button" class="btn btn-primary" id="add-address">
            Add Address
        </button>
        <div id="phones-container">
            <br />
            {{ phone_formset.management_form }}
            {% for form in phone_formset %}
            <div class="phone-form">
                <div class="input-button-container">
                    {{ form.as_p }}
                    <button type="button" class="btn btn-danger remove-phone">
                        Remove Phone
                    </button>
                </div>
            </div>
            {% endfor %}
        </div>
        <br>
        <button type="button" class="btn btn-primary" id="add-phone">
            Add Phone
        </button>
        <br />
        <br />
        <a href="{% url 'view_staff' %}" class="btn btn-secondary">Back</a>
        <button type="submit" class="btn btn-success">Save Staff Member</button>
        <br />
    </form>
</div>
<script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>

<script>
    $(document).ready(function () {
        function togglePilotNumField() {
            var staffType = $('#id_TYPE').val();
            if (staffType === 'Pilot') {
                $('#id_pilotnum').show();
            } else {
                $('#id_pilotnum').hide();
            }
        }

        $('#id_TYPE').change(togglePilotNumField);
        togglePilotNumField(); // Initial check

        // Add address
        $("#add-address").click(function () {
            var container = $("#addresses-container");
            var totalForms = container.find("input[name$='-ADDRESSDETAILS']").length;
            var newForm = container.find("div.address-form:first").clone(true);
            newForm.find("input").val("");
            newForm.find("label").attr("for", function () {
                return $(this)
                    .attr("for")
                    .replace("-" + (totalForms - 1) + "-", "-" + totalForms + "-");
            });
            newForm.find("input").attr("id", function () {
                return $(this)
                    .attr("id")
                    .replace("-" + (totalForms - 1) + "-", "-" + totalForms + "-");
            });
            container.append(newForm);
            toggleRemoveButtons();
        });

        // Remove address
        $(document).on("click", ".remove-address", function () {
            var totalForms = $("#addresses-container").find(
                "input[name$='-ADDRESSDETAILS']"
            ).length;
            if (totalForms > 1) {
                $(this).closest(".address-form").remove();
            }
            toggleRemoveButtons();
        });

        // Add phone
        $("#add-phone").click(function () {
            var container = $("#phones-container");
            var totalForms = container.find("input[name$='-PHONE']").length;
            var newForm = container.find("div.phone-form:first").clone(true);
            newForm.find("input").val("");
            newForm.find("label").attr("for", function () {
                return $(this)
                    .attr("for")
                    .replace("-" + (totalForms - 1) + "-", "-" + totalForms + "-");
            });
            newForm.find("input").attr("id", function () {
                return $(this)
                    .attr("id")
                    .replace("-" + (totalForms - 1) + "-", "-" + totalForms + "-");
            });
            container.append(newForm);
            toggleRemoveButtons();
        });

        // Remove phone
        $(document).on("click", ".remove-phone", function () {
            var totalForms = $("#phones-container").find(
                "input[name$='-PHONE']"
            ).length;
            if (totalForms > 1) {
                $(this).closest(".phone-form").remove();
            }
            toggleRemoveButtons();
        });

        // Toggle remove buttons
        function toggleRemoveButtons() {
            var addressForms = $("#addresses-container").find(".address-form");
            var phoneForms = $("#phones-container").find(".phone-form");
            if (addressForms.length === 1) {
                addressForms.find(".remove-address").hide();
            } else {
                addressForms.find(".remove-address").show();
            }
            if (phoneForms.length === 1) {
                phoneForms.find(".remove-phone").hide();
            } else {
                phoneForms.find(".remove-phone").show();
            }
        }

        // Initial toggle
        toggleRemoveButtons();
    });
</script>

{% endblock %}

website/templates/base.html
<!doctype html>
<html lang="en">

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Airline Database</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0-beta3/css/all.min.css">
    <style>
        .header-container {
            display: flex;
            align-items: center;
            justify-content: space-between;
            margin-bottom: 20px;
        }

        .header-container h1 {
            margin: 0;
        }

        .add-record-btn {
            display: flex;
            align-items: center;
            text-decoration: none;
            color: white;
        }

        .add-record-btn i {
            margin-right: 5px;
        }

        .phone-form,
        .address-form {
            margin-bottom: 10px;
        }

        .input-button-container {
            display: flex;
            align-items: center;
        }

        .input-button-container .btn {
            margin-left: 10px;
        }

        .input-button-container p {
            margin: 0;
            flex: 1;
            /* Allow p elements to grow and fill available space */
        }

        .input-button-container p input {
            width: 100%;
            /* Ensure the input element takes full width of the p element */
            box-sizing: border-box;
            /* Include padding and border in element's total width */
        }
    </style>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/moment.js/2.24.0/moment.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.3.1/js/bootstrap.bundle.min.js"></script>
    <script
        src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datetimepicker/4.17.47/js/bootstrap-datetimepicker.min.js"></script>
</head>

<body>
    {% include 'navbar.html' %}
    <div class="container">
        <br>
        {% if messages %}
        {% for message in messages %}
        <div class="alert alert-warning alert-dismissible fade show" role="alert">
            {{message}}
            <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
        </div>
        {% endfor %}
        {% endif %}
        {% block content %}
        {% endblock%}
    </div>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz"
        crossorigin="anonymous"></script>
</body>

</html>

website/templates/home.html
{% extends 'base.html' %}
{%block content %}



{% if user.is_authenticated %}

<div class="header-container">
    <h1>Flights</h1>
    {% if user.is_superuser %}
    <a href="{% url 'add_flight' %}" class="btn btn-primary add-record-btn">
        <i class="fas fa-plus"></i> Add Flight
    </a>
    {% endif %}
</div>
<table class="table table-striped table-hover table-bordered border-secondary">
    <thead class="table-primary">
        <tr>
            <th scope="col">Flight Number</th>
            <th scope="col">Origin</th>
            <th scope="col">Destination</th>
            <th scope="col">Departure Time</th>
            <th scope="col">Arrival Time</th>
            <th scope="col">Pilot</th>
            <th scope="col">Plane ID</th>
        </tr>
    </thead>
    <tbody>
        {% if flights %}
        {% for flight in flights %}
        <tr>
            <td><a href="{% url 'view_flight' flight.FLIGHTNUM %}">{{ flight.FLIGHTNUM }}</a></td>
            <td><a href="{% url 'view_city' flight.ORIGINCITYCODE.CITYCODE %}">{{ flight.ORIGINCITYCODE.CITYCODE }}</a>
            </td>
            <td><a href="{% url 'view_city' flight.DESTCITYCODE.CITYCODE %}">{{ flight.DESTCITYCODE.CITYCODE }}</a></td>
            <td>{{ flight.DEPTIME }}</td>
            <td>{{ flight.ARRTIME }}</td>
            <td><a href="{% url 'view_staff_member' flight.PILOTNUM.EMPNUM.EMPNUM %}">{{ flight.PILOTNUM.PILOTNUM }}</a>
            </td>
            <td><a href="{% url 'view_plane' flight.PLANENUM.SERIALNUM %}">{{ flight.PLANENUM.SERIALNUM }}</a></td>
        </tr>
        {%endfor%}
        {% endif %}
    </tbody>
</table>
{% if user.is_superuser %}
<a href="{% url 'list_users' %}" class="btn btn-primary add-record-btn" style="max-width: max-content;">
    Admin Management
</a>
{% endif %}

<div class="col-md-6 offset-md-3"></div>
{% else %}
<h1>Login</h1>
<br />
<form method="POST" action="{% url 'home' %}">
    {% csrf_token %}
    <form>
        <div class="mb-3">
            <input type="text" class="form-control" name="username" placeholder="Username" required>
        </div>
        <div class="mb-3">
            <input type="password" class="form-control" name="password" placeholder="Password" required>
        </div>
        <br />
        <button type="submit" class="btn btn-primary">Login</button>
    </form>

</form>

{% endif %}

</div>


{% endblock %}

website/templates/navbar.html
<nav class="navbar navbar-expand-lg sticky-top navbar-dark bg-dark">
  <div class="container-fluid">
    <a class="navbar-brand" href="{% url 'home' %}">Airline Management</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavAltMarkup"
      aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
      <div class="navbar-nav">
        {% if user.is_authenticated %}
        <a class="nav-link" href="{% url 'logout' %}">Logout</a>
        <a class="nav-link" href="{% url 'view_planes' %}">Planes</a>
        <!--<a class="nav-link" href="{% url 'view_pilots' %}">Pilots</a>-->
        <a class="nav-link" href="{% url 'view_staff' %}">Staff</a>
        <a class="nav-link" href="{% url 'view_cities' %}">Cities</a>
        <a class="nav-link" href="{% url 'view_passengers' %}">Passengers</a>
        {% else %}
        <a class="nav-link" href="{% url 'register' %}">Register</a>
        <a class="nav-link" href="{% url 'home' %}">Login</a>
        {% endif %}
      </div>
    </div>
  </div>
</nav>

website/templates/planes.html
{% extends 'base.html' %}
{%block content %}

<div class="col-md-6 offset-md-3">

{% if user.is_authenticated %}

<div class="header-container">
    <h1>Planes</h1>
    {% if user.is_superuser %}
    <a href="{% url 'add_plane' %}" class="btn btn-primary add-record-btn">
        <i class="fas fa-plus"></i> Add Plane
    </a>
    {% endif %}
</div>

<table class="table table-striped table-hover table-bordered border-secondary">
    <thead class="table-primary">
        <tr>
            <th scope="col">Serial Number</th>
            <th scope="col">Manufacturer</th>
            <th scope="col">Model</th>
        </tr>
    </thead>
    <tbody>
        {% if planes %}
            {% for plane in planes %}
                <tr>
                    <td><a href="{% url 'view_plane' plane.SERIALNUM %}">{{ plane.SERIALNUM }}</a></td>
                    <td>{{ plane.MANUFACTURER }}</td>
                    <td>{{ plane.MODEL }}</td>
                </tr>   
            {%endfor%}
        {% endif %}
    </tbody>
</table>

{% else %}
<div>Log In!</div>

{% endif %}

</div>


{% endblock %}

website/templates/update_pilot.html
{% extends 'base.html' %}
{% block content %}

<div class="col-md-6 offset-md-3">
    <h1>Update Pilot</h1>
    <br>

    <form method="POST">
        {% csrf_token %}

        {{ form.as_p }}
        <br>
        <a onclick="history.back()" class="btn btn-secondary">Back</a>
        <button type="submit" class="btn btn-primary">Update Pilot</button>


    </form>

</div>
{%endblock%}

website/templates/update_staff_member.html
{% extends 'base.html' %}
{% block content %}

<div class="col-md-6 offset-md-3">
    <h1>Update Staff Member {{ employee_num }}</h1>
    <br>

    <form method="POST">
        {% csrf_token %}

        {{ form.as_p }}
        <br>
        <a href="{% url 'view_staff_member' employee_num %}" class="btn btn-secondary">Back</a>
        <button type="submit" class="btn btn-primary">Update Staff Member</button>


    </form>

</div>
{%endblock%}

website/templates/user_form.html
{% extends 'base.html' %}
{%block content %}

{% if user.is_authenticated %}
<div class="col-md-6 offset-md-3">
    <h1>{{ title }}</h1>
    <br>

    <form method="POST">
        {% csrf_token %}

        {{ form.as_p }}
        <br>
        <a href="{% url 'list_users' %}" class="btn btn-secondary">Back</a>
        <button type="submit" class="btn btn-primary">Save</button>
    </form>

</div>


{%endif%}
{%endblock%}